"""baseline: coverai schema as of 2026-07-06

The canonical schema as coverai/models.py defines it. The live coverai.db
was stamped at this revision rather than upgraded, so it carries two known
pre-baseline fossils this migration does not create on fresh databases:

- offers.dedupe_hash has a leftover single-column UNIQUE constraint from
  before user_id existed (superseded by idx_offers_user_dedupe).
- Columns added over time via storage._ensure_column (user_id on offers,
  explorer_runs, queue_items, sms_reports, events) lack their FOREIGN KEY
  to users, because SQLite's ALTER TABLE cannot add one.

Reconciling those is a future migration's job, not the baseline's.

Revision ID: 69f48f441dc6
Revises:
Create Date: 2026-07-06 10:47:57.313674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f48f441dc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platforms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), server_default='', nullable=False),
    sa.Column('login_url', sa.String(), server_default='', nullable=False),
    sa.Column('kind', sa.String(), server_default='job_board', nullable=False),
    sa.Column('enabled', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), server_default='', nullable=False),
    sa.Column('display_name', sa.String(), server_default='', nullable=False),
    sa.Column('role', sa.String(), server_default='user', nullable=False),
    sa.Column('phone', sa.String(), server_default='', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), server_default='julien', nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('subject_type', sa.String(), server_default='', nullable=False),
    sa.Column('subject_id', sa.String(), server_default='', nullable=False),
    sa.Column('payload_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('explorer_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), server_default='julien', nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('config_path', sa.String(), server_default='', nullable=False),
    sa.Column('started_at', sa.String(), nullable=False),
    sa.Column('completed_at', sa.String(), server_default='', nullable=False),
    sa.Column('offers_found', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('offers_new', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('offers_reported', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.Text(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('explorer_runs', schema=None) as batch_op:
        batch_op.create_index('idx_runs_user_started', ['user_id', 'started_at'], unique=False)

    op.create_table('offers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), server_default='julien', nullable=False),
    sa.Column('dedupe_hash', sa.String(), nullable=False),
    sa.Column('url', sa.String(), server_default='', nullable=False),
    sa.Column('title', sa.String(), server_default='', nullable=False),
    sa.Column('company', sa.String(), server_default='', nullable=False),
    sa.Column('location', sa.String(), server_default='', nullable=False),
    sa.Column('source', sa.String(), server_default='', nullable=False),
    sa.Column('raw_text', sa.Text(), server_default='', nullable=False),
    sa.Column('snippet', sa.Text(), server_default='', nullable=False),
    sa.Column('score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.String(), server_default='new', nullable=False),
    sa.Column('cleanup_status', sa.String(), server_default='ok', nullable=False),
    sa.Column('canonical_ref', sa.String(), server_default='', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('last_seen_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index('idx_offers_user_dedupe', ['user_id', 'dedupe_hash'], unique=True)
        batch_op.create_index('idx_offers_user_score', ['user_id', 'score', 'updated_at'], unique=False)

    op.create_table('queue_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), server_default='julien', nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('subject_type', sa.String(), server_default='', nullable=False),
    sa.Column('subject_id', sa.String(), server_default='', nullable=False),
    sa.Column('payload_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), server_default='julien', nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), server_default='', nullable=False),
    sa.Column('text', sa.Text(), server_default='', nullable=False),
    sa.Column('response_text', sa.Text(), server_default='', nullable=False),
    sa.Column('command', sa.String(), server_default='', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_messages', schema=None) as batch_op:
        batch_op.create_index('idx_sms_messages_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('user_platform_accounts',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('platform_id', sa.String(), nullable=False),
    sa.Column('login_url', sa.String(), server_default='', nullable=False),
    sa.Column('profile_dir', sa.String(), server_default='', nullable=False),
    sa.Column('status', sa.String(), server_default='not_connected', nullable=False),
    sa.Column('last_login_check_at', sa.String(), server_default='', nullable=False),
    sa.Column('metadata_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'platform_id')
    )
    op.create_table('application_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), server_default='julien', nullable=False),
    sa.Column('offer_id', sa.String(), nullable=False),
    sa.Column('queue_item_id', sa.String(), server_default='', nullable=False),
    sa.Column('company', sa.String(), server_default='', nullable=False),
    sa.Column('role_title', sa.String(), server_default='', nullable=False),
    sa.Column('status', sa.String(), server_default='preparing', nullable=False),
    sa.Column('readiness_percent', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('questions_total', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('questions_answered', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('questions_needs_user', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('questions_low_confidence', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('artifacts_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('strategy_text', sa.Text(), server_default='', nullable=False),
    sa.Column('last_action', sa.String(), server_default='', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_application_tasks_offer', ['offer_id'], unique=False)
        batch_op.create_index('idx_application_tasks_user_offer', ['user_id', 'offer_id'], unique=True)
        batch_op.create_index('idx_application_tasks_user_status', ['user_id', 'status', 'updated_at'], unique=False)

    op.create_table('sms_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), server_default='julien', nullable=False),
    sa.Column('offer_id', sa.String(), nullable=False),
    sa.Column('number', sa.String(), server_default='', nullable=False),
    sa.Column('text', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.String(), server_default='', nullable=False),
    sa.Column('response_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), server_default='julien', nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('field_type', sa.String(), server_default='text', nullable=False),
    sa.Column('required', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('answer', sa.Text(), server_default='', nullable=False),
    sa.Column('answer_source', sa.String(), server_default='unknown', nullable=False),
    sa.Column('confidence', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(), server_default='detected', nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_questions', schema=None) as batch_op:
        batch_op.create_index('idx_application_questions_app', ['application_id', 'status'], unique=False)

    # ### end Alembic commands ###

    # Views are not table metadata, so autogenerate cannot emit them.
    op.execute(
        "CREATE VIEW IF NOT EXISTS offers_clean AS "
        "SELECT * FROM offers WHERE cleanup_status NOT IN ('noise', 'duplicate')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW IF EXISTS offers_clean")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_questions', schema=None) as batch_op:
        batch_op.drop_index('idx_application_questions_app')

    op.drop_table('application_questions')
    op.drop_table('sms_reports')
    with op.batch_alter_table('application_tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_application_tasks_user_status')
        batch_op.drop_index('idx_application_tasks_user_offer')
        batch_op.drop_index('idx_application_tasks_offer')

    op.drop_table('application_tasks')
    op.drop_table('user_platform_accounts')
    with op.batch_alter_table('sms_messages', schema=None) as batch_op:
        batch_op.drop_index('idx_sms_messages_user_created')

    op.drop_table('sms_messages')
    op.drop_table('queue_items')
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index('idx_offers_user_score')
        batch_op.drop_index('idx_offers_user_dedupe')

    op.drop_table('offers')
    with op.batch_alter_table('explorer_runs', schema=None) as batch_op:
        batch_op.drop_index('idx_runs_user_started')

    op.drop_table('explorer_runs')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('platforms')
    # ### end Alembic commands ###
